syntax = "proto3";
package cosmos.multisig.v1;

import "gogoproto/gogo.proto";
import "cosmos/multisig/v1/multisig.proto";
import "amino/amino.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/multisig/types";

// GenesisState defines the multisig module's genesis state.
message GenesisState {
  Params            params    = 1 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];
  repeated Account  accounts  = 2;
  repeated Proposal proposals = 3;
  repeated Vote     votes     = 4;
}
