syntax = "proto3";
package cosmos.multisig.v1;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos_proto/cosmos.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "cosmos/multisig/v1/multisig.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/multisig/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/cosmos/multisig/v1/params";
  }
  // Account queries a multisig account.
  rpc Account(QueryAccountRequest) returns (QueryAccountResponse) {
    option (google.api.http).get = "/cosmos/multisig/v1/account";
  }
  // Proposals queries all the multisig account's proposals.
  rpc Proposals(QueryProposalsRequest) returns (QueryProposalsResponse) {
    option (google.api.http).get = "/cosmos/multisig/v1/proposals";
  }
  // Proposals queries a single multisig account's proposal.
  rpc Proposal(QueryProposalRequest) returns (QueryProposalResponse) {
    option (google.api.http).get = "/cosmos/multisig/v1/proposal";
  }
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1 [(gogoproto.nullable) = false];
}

message QueryAccountRequest {
  string address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
}

message QueryAccountResponse {
  Account account = 1;
}

message QueryProposalsRequest {
  string account_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
}

message QueryProposalsResponse {
  repeated Proposal proposals = 1 [(gogoproto.nullable) = false];
}

message QueryProposalRequest {
  string account_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  uint64 proposal_id     = 2;
}

message QueryProposalResponse {
  Proposal      proposal = 1 [(gogoproto.nullable) = false];
  repeated Vote votes    = 2 [(gogoproto.nullable) = false];
}
